import type { MediaSource } from '../types.js';

/**
 * Registry of supported global media sources.
 *
 * Adding a new source is as simple as appending an entry here — the rest of
 * the pipeline (fetcher, dedupe, analyzer) is source-agnostic.
 */
export const SOURCES: MediaSource[] = [
  {
    domain: 'aa.com.tr',
    nameCN: '阿纳多卢通讯社',
    country: 'Turkey',
    flag: '🇹🇷',
    accessibleInChina: true,
    language: 'en',
    feeds: ['https://www.aa.com.tr/en/rss/default?cat=guncel'],
  },
  {
    domain: 'abc.net.au',
    nameCN: '澳大利亚广播公司',
    country: 'Australia',
    flag: '🇦🇺',
    accessibleInChina: false,
    language: 'en',
    feeds: ['https://www.abc.net.au/news/feed/45910/rss.xml'],
  },
  {
    domain: 'aljazeera.com',
    nameCN: '半岛电视台',
    country: 'Qatar',
    flag: '🇶🇦',
    accessibleInChina: true,
    language: 'en',
    feeds: ['https://www.aljazeera.com/xml/rss/all.xml'],
  },
  {
    domain: 'bbc.com',
    nameCN: '英国广播公司',
    country: 'UK',
    flag: '🇬🇧',
    accessibleInChina: false,
    language: 'en',
    feeds: ['https://feeds.bbci.co.uk/news/world/rss.xml'],
  },
  {
    domain: 'cbc.ca',
    nameCN: '加拿大广播公司',
    country: 'Canada',
    flag: '🇨🇦',
    accessibleInChina: false,
    language: 'en',
    feeds: ['https://www.cbc.ca/webfeed/rss/rss-topstories'],
  },
  {
    domain: 'chinanews.com',
    nameCN: '中国新闻网',
    country: 'China',
    flag: '🇨🇳',
    accessibleInChina: true,
    language: 'zh',
    feeds: ['https://www.chinanews.com.cn/rss/scroll-news.xml'],
  },
  {
    domain: 'dw.com',
    nameCN: '德国之声',
    country: 'Germany',
    flag: '🇩🇪',
    accessibleInChina: false,
    language: 'en',
    feeds: ['https://rss.dw.com/rdf/rss-en-all'],
  },
  {
    domain: 'elpais.com',
    nameCN: '国家报',
    country: 'Spain',
    flag: '🇪🇸',
    accessibleInChina: false,
    language: 'es',
    feeds: ['https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada'],
  },
  {
    domain: 'investing.com',
    nameCN: '英为财情',
    country: 'International',
    flag: '🌍',
    accessibleInChina: true,
    language: 'en',
    feeds: ['https://www.investing.com/rss/news.rss'],
  },
  {
    domain: 'news.cn',
    nameCN: '新华网',
    country: 'China',
    flag: '🇨🇳',
    accessibleInChina: true,
    language: 'zh',
    feeds: ['http://www.news.cn/world/news_world.xml'],
  },
  {
    domain: 'nhk.or.jp',
    nameCN: '日本广播协会',
    country: 'Japan',
    flag: '🇯🇵',
    accessibleInChina: true,
    language: 'ja',
    feeds: ['https://www3.nhk.or.jp/rss/news/cat0.xml'],
  },
  {
    domain: 'ntv.com.tr',
    nameCN: '土耳其主流媒体 NTV',
    country: 'Turkey',
    flag: '🇹🇷',
    accessibleInChina: true,
    language: 'tr',
    feeds: ['https://www.ntv.com.tr/dunya.rss'],
  },
  {
    domain: 'rfi.fr',
    nameCN: '法国国际广播电台',
    country: 'France',
    flag: '🇫🇷',
    accessibleInChina: false,
    language: 'fr',
    feeds: ['https://www.rfi.fr/fr/rss'],
  },
  {
    domain: 'tass.com',
    nameCN: '塔斯社',
    country: 'Russia',
    flag: '🇷🇺',
    accessibleInChina: true,
    language: 'en',
    feeds: ['https://tass.com/rss/v2.xml'],
  },
  {
    domain: 'voanews.com',
    nameCN: '美国之音',
    country: 'USA',
    flag: '🇺🇸',
    accessibleInChina: false,
    language: 'en',
    feeds: ['https://www.voanews.com/api/zmgqoe$omi'],
  },
  {
    domain: 'theguardian.com',
    nameCN: '卫报',
    country: 'UK',
    flag: '🇬🇧',
    accessibleInChina: false,
    language: 'en',
    feeds: ['https://www.theguardian.com/world/rss'],
  },
  {
    domain: 'nytimes.com',
    nameCN: '纽约时报',
    country: 'USA',
    flag: '🇺🇸',
    accessibleInChina: false,
    language: 'en',
    feeds: ['https://rss.nytimes.com/services/xml/rss/nyt/World.xml'],
  },
  {
    domain: 'cnn.com',
    nameCN: '美国有线电视新闻网',
    country: 'USA',
    flag: '🇺🇸',
    accessibleInChina: false,
    language: 'en',
    feeds: ['http://rss.cnn.com/rss/edition_world.rss'],
  },
  {
    domain: 'washingtonpost.com',
    nameCN: '华盛顿邮报',
    country: 'USA',
    flag: '🇺🇸',
    accessibleInChina: false,
    language: 'en',
    feeds: ['https://feeds.washingtonpost.com/rss/world'],
  },
  {
    domain: 'france24.com',
    nameCN: '法国24',
    country: 'France',
    flag: '🇫🇷',
    accessibleInChina: false,
    language: 'en',
    feeds: ['https://www.france24.com/en/rss'],
  },
  {
    domain: 'lemonde.fr',
    nameCN: '世界报',
    country: 'France',
    flag: '🇫🇷',
    accessibleInChina: false,
    language: 'fr',
    feeds: ['https://www.lemonde.fr/rss/une.xml'],
  },
  {
    domain: 'spiegel.de',
    nameCN: '明镜',
    country: 'Germany',
    flag: '🇩🇪',
    accessibleInChina: false,
    language: 'en',
    feeds: ['https://www.spiegel.de/international/index.rss'],
  },
  {
    domain: 'scmp.com',
    nameCN: '南华早报',
    country: 'Hong Kong',
    flag: '🇭🇰',
    accessibleInChina: false,
    language: 'en',
    feeds: ['https://www.scmp.com/rss/91/feed'],
  },
  {
    domain: 'timesofindia.indiatimes.com',
    nameCN: '印度时报',
    country: 'India',
    flag: '🇮🇳',
    accessibleInChina: true,
    language: 'en',
    feeds: ['https://timesofindia.indiatimes.com/rssfeedstopstories.cms'],
  },
  {
    domain: 'thehindu.com',
    nameCN: '印度教徒报',
    country: 'India',
    flag: '🇮🇳',
    accessibleInChina: true,
    language: 'en',
    feeds: ['https://www.thehindu.com/news/international/feeder/default.rss'],
  },
  {
    domain: 'yna.co.kr',
    nameCN: '韩联社',
    country: 'South Korea',
    flag: '🇰🇷',
    accessibleInChina: true,
    language: 'en',
    feeds: ['https://en.yna.co.kr/RSS/news.xml'],
  },
  {
    domain: 'straitstimes.com',
    nameCN: '海峡时报',
    country: 'Singapore',
    flag: '🇸🇬',
    accessibleInChina: true,
    language: 'en',
    feeds: ['https://www.straitstimes.com/news/world/rss.xml'],
  },
  {
    domain: 'jpost.com',
    nameCN: '耶路撒冷邮报',
    country: 'Israel',
    flag: '🇮🇱',
    accessibleInChina: true,
    language: 'en',
    feeds: ['https://www.jpost.com/rss/rssfeedsfrontpage.aspx'],
  },
  {
    domain: 'g1.globo.com',
    nameCN: '环球新闻',
    country: 'Brazil',
    flag: '🇧🇷',
    accessibleInChina: true,
    language: 'pt',
    feeds: ['http://g1.globo.com/dynamo/mundo/rss2.xml'],
  },
  {
    domain: 'sputnikglobe.com',
    nameCN: '俄罗斯卫星通讯社',
    country: 'Russia',
    flag: '🇷🇺',
    accessibleInChina: true,
    language: 'en',
    feeds: ['https://sputnikglobe.com/export/rss2/archive/index.xml'],
  },
  {
    domain: 'rt.com',
    nameCN: 'RT 国际',
    country: 'Russia',
    flag: '🇷🇺',
    accessibleInChina: true,
    language: 'en',
    feeds: ['https://www.rt.com/rss/news/'],
  },
  {
    domain: 'cgtn.com',
    nameCN: '中国国际电视台',
    country: 'China',
    flag: '🇨🇳',
    accessibleInChina: true,
    language: 'en',
    feeds: ['https://www.cgtn.com/subscribe/rss/section/world.xml'],
  },
  {
    domain: 'globaltimes.cn',
    nameCN: '环球时报',
    country: 'China',
    flag: '🇨🇳',
    accessibleInChina: true,
    language: 'en',
    feeds: ['https://www.globaltimes.cn/rss/outbrain.xml'],
  },

  // ── AI 行业 ────────────────────────────────────────────────────────────────
  {
    domain: 'techcrunch.com',
    nameCN: 'TechCrunch（AI 频道）',
    country: 'International',
    flag: '🤖',
    accessibleInChina: false,
    language: 'en',
    feeds: ['https://techcrunch.com/category/artificial-intelligence/feed/'],
  },
  {
    domain: 'technologyreview.com',
    nameCN: '麻省理工科技评论（AI）',
    country: 'International',
    flag: '🤖',
    accessibleInChina: false,
    language: 'en',
    feeds: ['https://www.technologyreview.com/topic/artificial-intelligence/feed'],
  },
  {
    domain: 'arstechnica.com',
    nameCN: 'Ars Technica（AI）',
    country: 'International',
    flag: '🤖',
    accessibleInChina: false,
    language: 'en',
    feeds: ['https://arstechnica.com/ai/feed/'],
  },
  {
    domain: 'venturebeat.com',
    nameCN: 'VentureBeat（AI）',
    country: 'International',
    flag: '🤖',
    accessibleInChina: false,
    language: 'en',
    feeds: ['https://venturebeat.com/category/ai/feed/'],
  },
  {
    domain: 'wired.com',
    nameCN: 'Wired（AI）',
    country: 'International',
    flag: '🤖',
    accessibleInChina: false,
    language: 'en',
    feeds: ['https://www.wired.com/feed/tag/ai/latest/rss'],
  },

  // ── GitHub 平台动态 ────────────────────────────────────────────────────────
  {
    domain: 'github.blog',
    nameCN: 'GitHub 官方博客',
    country: 'International',
    flag: '🐙',
    accessibleInChina: true,
    language: 'en',
    feeds: ['https://github.blog/feed/'],
  },
  {
    domain: 'github.blog/changelog',
    nameCN: 'GitHub Changelog',
    country: 'International',
    flag: '🐙',
    accessibleInChina: true,
    language: 'en',
    feeds: ['https://github.blog/changelog/feed/'],
  },
  {
    domain: 'github.blog/engineering',
    nameCN: 'GitHub 工程博客',
    country: 'International',
    flag: '🐙',
    accessibleInChina: true,
    language: 'en',
    feeds: ['https://github.blog/category/engineering/feed/'],
  },
];

export function getSourceByDomain(domain: string): MediaSource | undefined {
  return SOURCES.find((s) => s.domain === domain);
}
